# fly.toml  ────────────────────────────────────────────────────────────
app            = "sharp-young-resonance-77"
primary_region = "sea"

[build]
  dockerfile = "Dockerfile"

[mounts]                    # ❶  volume that holds wa_token + gmail_hist
  source      = "wa_data"
  destination = "/data"

[env]
  PYTHONUNBUFFERED = "1"

[processes]                 # one long-lived poller + the hourly settler
  worker  = "poetry run python -m worker"
  settler = "poetry run python -m settler --hourly"

[[vm]]                      # tiny shared-CPU instance for both procs
  cpu_kind = "shared"
  cpus     = 1
  memory   = "1gb"