# fly.toml ── minimal & works
app            = "sharp-young-resonance-77"
primary_region = "sea"

[build]
  dockerfile = "Dockerfile"

[[mounts]]
  source      = "wa_data"    # ← same volume name
  destination = "/data"      #   one block, no “processes =”

[env]
  PYTHONUNBUFFERED = "1"

[processes]
  worker  = "poetry run python -m worker"
  settler = "poetry run python -m settler --hourly"

[[vm]]
  cpu_kind = "shared"
  cpus     = 1
  memory   = "1gb"