# fly.toml
app            = "sharp-young-resonance-77"
primary_region = "sea"

[build]
  dockerfile = "Dockerfile"

# ─── this is the bit that actually wires the volume in ───
[mounts]
  source      = "wa_data"     # the volume name you created
  destination = "/data"       # path inside the container
  processes   = ["worker", "settler"]   # attach to BOTH groups
# ─────────────────────────────────────────────────────────

[env]
  PYTHONUNBUFFERED = "1"

[processes]
  worker  = "poetry run python -m worker"
  settler = "poetry run python -m settler --hourly"

[[vm]]
  cpu_kind = "shared"
  cpus     = 1
  memory   = "1gb"