app            = "sharp-young-resonance-77"
primary_region = "sea"

[build]
  dockerfile = "Dockerfile"

#────────────────────  volumes  ────────────────────
[[mounts]]                     # volume for the worker process-group
  source      = "wa_data"      # <- exactly as in `fly volumes list`
  destination = "/data"
  processes   = ["worker"]

[[mounts]]                     # volume for the settler process-group
  source      = "wa_data_settler"
  destination = "/data"
  processes   = ["settler"]
#────────────────────────────────────────────────────

[env]
  PYTHONUNBUFFERED = "1"

[processes]
  worker  = "poetry run python -m worker"
  settler = "poetry run python -m settler --hourly"

[[vm]]
  cpu_kind = "shared"
  cpus     = 1
  memory   = "1gb"