app            = "sharp-young-resonance-77"
primary_region = "sea"

[build]
  dockerfile = "Dockerfile"

# ------------------------------------------------------------------
# One volume, mounted ONLY on the always-on worker Machine
# ------------------------------------------------------------------
[mounts]
  source      = "wa_data"   # you already created this volume
  destination = "/data"     # worker reads /data/wa_token.json + .gmail_hist
  processes   = ["worker"]  # attach to worker only

[env]
  PYTHONUNBUFFERED = "1"

# ------------------------------------------------------------------
# Two distinct process groups → Fly will spin up two Machines
# ------------------------------------------------------------------
[processes]
  # long-lived Gmail poller / WA bet placer
  worker  = "poetry run python -m worker"

  # one-shot job that sleeps internally and exits;
  # wakes up again each hour on the scheduler you coded
  settler = "poetry run python -m settler --hourly"

[[vm]]
  cpu_kind = "shared"
  cpus     = 1
  memory   = "1gb"