# fly.toml ─── one-machine/one-volume layout
app            = "sharp-young-resonance-77"
primary_region = "sea"

[build]
dockerfile = "Dockerfile"

# ----- persistent storage ----------------------------------------------
[[mounts]]
source      = "wa_data"     # the single volume you already created
destination = "/data"       # visible inside the container as /data
# ------------------------------------------------------------------------

[env]
PYTHONUNBUFFERED = "1"

# only ONE process-group.  It runs start.sh, which launches both tasks.
[processes]
app = "/start.sh"

[[vm]]
cpu_kind = "shared"
cpus     = 1
memory   = "1gb"