# fly.toml ──────────────────────────────────────────────
app            = "sharp-young-resonance-77"
primary_region = "sea"

[build]
  dockerfile = "Dockerfile"

# ───────  VOLUME MOUNT  ───────
[[mounts]]                     # ← double square-brackets **required**
  source      = "wa_data"
  destination = "/data"
  processes   = ["worker", "settler"]  # attach to both groups
  # (omit this line if you really want it mounted to *all* groups)

[env]
  PYTHONUNBUFFERED = "1"

[processes]
  worker  = "poetry run python -m worker"
  settler = "poetry run python -m settler --hourly"

[[vm]]
  cpu_kind = "shared"
  cpus     = 1
  memory   = "1gb"